version: "3.4"
services:
  poste:
    image: analogic/poste.io
    restart: always
    ports:
      - "8080:80"
      - "4433:443"
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    volumes:
      - /mnt/mail:/data
    environment:
      - HTTPS=ON
      - DISABLE_CLAMAV=TRUE
