version: "3.4"
services:
  poste:
    image: analogic/poste.io
    restart: always
    ports:
      - "8080:8080"
      - "4433:4433"
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    volumes:
      - /mnt/mail:/data
    environment:
      - HTTPS=OFF
      - DISABLE_CLAMAV=TRUE
      - VIRTUAL_HOST=mail.devsign.org